Create how-to-refund-vm
Stella-IT/docs pull request #32
Opened 2022-01-11 04:03 UTC by ckfejrdld

---
title: 가상 머신을 잘못 구매했어요
description: 가상 머신의 중도 해지에 관해 알아봅시다

category: FAQ/Payments
---

Stella IT 서비스는 중도 해지가 가능합니다. (일부 상품 제외)
  
중도 해지를 원하시는 경우, [Stella IT Console 지원](https://console.stella-it.com/support) 섹션에 접속하신 후 `지원코드 발급`을 이용하여 지원코드를 받급 받으신 후, 위에 '상담원을 통한 지원' 중 한가지를 선택하셔서 발급하신 지원코드 및 삭제를 원하시는 가상 머신을 말해주세요.

중도 해지 시 환불 금액은 아래를 참고해주세요.
  
![refund](https://user-images.githubusercontent.com/70272129/148869697-290e8013-6332-411c-bdce-3a085f2f2315.png)

<alert type="warning">
환불 받을 수 있는 금액이 0 이하인 경우, 환불이 진행되지 않습니다.
</alert>

<alert type="warning">
반복적인 중도 해지 요청은 금지됩니다.

* 반복적인 중도 해지 요청은 회사의 인력 및 자원 낭비를 초래하므로, 반복적으로 중도 해지를 요청하는 경우 회사는 중도 해지 요청을 거부할 수 있습니다.
</alert>

2022-01-11 04:06 UTC, ldmsys commented on content/ko/faq/payments/how-to-refund-vm
> +title: 가상 머신을 잘못 구매했어요
VM 생성시 OS, 클러스터, 요금제 및 라벨 등을 잘못 선택한 것은 상담 센터를 통해 정정할 수 있기 때문에 `가상머신을 잘못 구매했어요`라는 title은 단순 정정이 가능한 경우에도 중도 해지를 유도할 수 있으므로 부적절합니다.

2022-01-11 04:07 UTC, ldmsys requested changes
VM 생성시 OS, 클러스터, 요금제 및 라벨 등을 잘못 선택한 것은 상담 센터를 통해 정정할 수 있기 때문에 `가상머신을 잘못 구매했어요`라는 title은 단순 정정이 가능한 경우에도 중도 해지를 유도할 수 있으므로 부적절합니다.

2022-02-05 14:58 UTC, Alex4386 commented
수정 사항 언제 반영되나요 ㅠㅠ

2022-02-05 14:59 UTC, Alex4386 commented
에라 모르겠다 CLOSE

2022-02-05 14:59 UTC, closed without merging