Update payments.md
Stella-IT/docs pull request #33
Opened 2022-01-11 04:06 UTC by ckfejrdld

---
title: Stella IT Payments
description: Stella IT Payments에 관련해 자주 묻는 질문들을 담았습니다.
category: FAQ
---

* [결제 수단 등록은 어떻게 하나요?](/faq/payments/how-to-set-billing-card)  
* [현금영수증/세금계산서 발행은 어떻게 해야되나요?](/faq/payments/how-to-issue-receipt) 
* [결제를 어떻게 하나요?](/faq/payments/how-to-make-a-purchase)
* [가상 머신을 잘못 구매했어요](/faq/payments/how-to-refund-vm)

2022-01-11 04:10 UTC, ldmsys requested changes
Refer #32

2022-01-11 04:10 UTC, ldmsys commented on content/ko/faq/payments.md
> +* [가상 머신을 잘못 구매했어요](/faq/payments/how-to-refund-vm)
Refer #32

2022-01-12 22:38 UTC, Alex4386 approved these changes, later dismissed
NICE :]

2022-02-05 14:59 UTC, Alex4386 commented
Closing PR due to stale status

2022-02-05 14:59 UTC, closed without merging